David/qubit tracking
qiboteam/qibolab_platforms_qrc pull request #54
Opened 2023-09-19 17:28 UTC by DavidSarlle

this PR contains modifications in the iqm5q and qw5q runcards in order to accommodate the parameters needed for flux routines fitting in qibocal PR https://github.com/qiboteam/qibocal/pull/519

The PR also fixes some small bugs found in iqm5 platform and the config needed for the new LO controlling the TWPA (replaced ERA LO by a R&S LO).

New characterization for q0 in iqm5q.

![imagen](https://github.com/qiboteam/qibolab_platforms_qrc/assets/39095664/c15cf705-b7e8-48fd-b704-71b2d08b1be2)

This PR can be merged as it is, without waiting for merging the qibocal PR (https://github.com/qiboteam/qibocal/pull/519).
The qibolab PR.

Please, merge qibolab PR https://github.com/qiboteam/qibolab/pull/581 in order to be able to access the new runcard paramters from the qubit object and be able to update them after fitting.

2023-09-20 10:51 UTC, Jacfomg requested changes
As you want to remove couplers this should be merged after #49.

2023-09-20 10:51 UTC, Jacfomg commented on iqm5q.py
> +TWPA_ADDRESS = "192.168.0.32"  # "192.168.0.210"
```suggestion
TWPA_ADDRESS = "192.168.0.32" 
```

Let's remove the old IP

2023-09-20 10:51 UTC, Jacfomg commented on iqm5q.py
> +        # qubits[q].readout = channels["L2-7"]
```suggestion

```
dead code

2023-09-20 11:50 UTC, DavidSarlle commented
> As you want to remove couplers this should be merged after #49.

I am removing the couplers because the platform in main and the runcard wasnot working with qibolab main. 

I think we should merge first this one and then add the info regarding the couplers. 

Are the parameters of your PR regarding the couplers and 2 qubit gates good? I suppouse that if we recharacterize the 5q, these information will be also modified...

2023-09-20 11:56 UTC, DavidSarlle commented on iqm5q.py
> +        # qubits[q].readout = channels["L2-7"]
done

2023-09-20 11:56 UTC, DavidSarlle commented on iqm5q.py
> +TWPA_ADDRESS = "192.168.0.32"  # "192.168.0.210"
done

2023-09-20 13:27 UTC, DavidSarlle commented
added characterization of q2 with assigment fidelity of 86.1% (fine tunning still pending, but isbetter than what is now in main)

![image](https://github.com/qiboteam/qibolab_platforms_qrc/assets/39095664/2f83e3ee-e636-4d41-9fb2-c484d658c5f8)

2023-09-21 11:38 UTC, Jacfomg commented
> > As you want to remove couplers this should be merged after #49.
> 
> I am removing the couplers because the platform in main and the runcard wasnot working with qibolab main.
> 
> I think we should merge first this one and then add the info regarding the couplers.
> 
> Are the parameters of your PR regarding the couplers and 2 qubit gates good? I suppouse that if we recharacterize the 5q, these information will be also modified...

They will be conflicting with https://github.com/qiboteam/qibolab/pull/575 and https://github.com/qiboteam/qibolab_platforms_qrc/pull/49 on how coupler based devices should have the calibration runcards

2023-09-22 08:21 UTC, DavidSarlle commented
added characterization of q2 with assignment fidelity of 75.1% (fine tunning still pending)

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/2440d62c-ab53-480a-b588-f7f749453f98/1c887c21-0868-435c-8ff0-1763cbf42c58/Untitled.png)

2023-09-26 09:41 UTC, DavidSarlle commented
The tests are not passing until we merge qibolab PR https://github.com/qiboteam/qibolab/pull/581 where the new qubit attributes has been introduced. As soon as we merge it, the test will pass.

2023-09-26 11:48 UTC, stavros11 commented
> The tests are not passing until we merge qibolab PR [qiboteam/qibolab#581](https://github.com/qiboteam/qibolab/pull/581) where the new qubit attributes has been introduced. As soon as we merge it, the test will pass.

For this we need to merge [qiboteam/qibolab#581](https://github.com/qiboteam/qibolab/pull/581) and **release** qibolab, because the workflow is using the stable release (to make sure that the default cluster environment works). In #56 I added a workflow that is using qibolab main to check such situations before releasing.

But we can still merge this when it's ready. I am hoping to make a qibolab release by the end of this week anyway.

2023-09-26 12:24 UTC, DavidSarlle commented
> > The tests are not passing until we merge qibolab PR [qiboteam/qibolab#581](https://github.com/qiboteam/qibolab/pull/581) where the new qubit attributes has been introduced. As soon as we merge it, the test will pass.
> 
> For this we need to merge [qiboteam/qibolab#581](https://github.com/qiboteam/qibolab/pull/581) and **release** qibolab, because the workflow is using the stable release (to make sure that the default cluster environment works). In #56 I added a workflow that is using qibolab main to check such situations before releasing.
> 
> But we can still merge this when it's ready. I am hoping to make a qibolab release by the end of this week anyway.

Thanks @stavros11 for the comments. From my side is ready. The characterization for 1q gates is done for q0, q1 and q2. The q3 and q4 are not well characterized becasue the fridge is not cold. 
The chip is not operative so, up to you, we can merge or wait until the new release of qibolab

2023-09-28 08:50 UTC, stavros11 commented
@DavidSarlle @Jacfomg since most interface changing PRs in qibolab have been merged, we should probably also merge this and #49 to sync with the changes. Of course the calibration doesn't matter anymore, but it will be helpful to have these runcards in main so that we are compatible with qibolab-main and we can start the recalibration without bugs.

My plan is to merge this first as it is introducing the new parameters and then merge #49 to sync with the coupler changes. Do you agree?

2023-09-28 11:09 UTC, DavidSarlle commented
I agree @stavros11 . Thanks.

2023-09-28 11:40 UTC, stavros11 approved these changes

2023-09-28 11:53 UTC, andrea-pasquale approved these changes

2023-09-28 12:10 UTC, merged